[package]
name = "tex2word-backend"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "../../README.md"
description = "tex2word OOXML back-end: IR -> .docx (fields, zip, images)"

[dependencies]
tex2word-ir.workspace = true
tex2word-math.workspace = true
