[package]
name = "tex2word-frontend"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "../../README.md"
description = "tex2word LaTeX front-end: LaTeX -> IR"

[dependencies]
tex2word-ir.workspace = true
